# environment.yml
name: llm_env
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4  # optional, if GPU available
  - cudatoolkit        # fallback for CPU/GPU compatibility
  - nvidia-ml-py=13.580.82
  - pip:
      - uv>=0.4.0
