name: Publish Model to Hub

on:
  workflow_dispatch:
    inputs:
      model_path:
        description: 'Path to model checkpoint'
        required: true
        default: './outputs/final_model'
      repo_name:
        description: 'HuggingFace repo name'
        required: true
      private:
        description: 'Make repo private'
        required: false
        default: 'true'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install huggingface_hub

    - name: Publish to Hub
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python scripts/publish_to_hub.py \
          --model-path ${{ github.event.inputs.model_path }} \
          --repo-name ${{ github.event.inputs.repo_name }} \
          --private ${{ github.event.inputs.private }}
